#pragma once
//메뉴 및 애니메이션 함수
#include "subFunc.h"

void print_box() {
	printf("                                                                           \n");
	printf("                                                                           \n");
	printf("                                     ######                                \n");
	printf("                                  ###......##                              \n");
	printf("                               ###...........##                            \n");
	printf("                            ###...............##                           \n");
	printf("                        ####....................#                          \n");
	printf("                       #....#................###l                          \n");
	printf("                      #......#............### ..l                          \n");
	printf("                     ##.......#........### .....l                          \n");
	printf("                     l ###....#.....### ........l                          \n");
	printf("                     l... ###.#..### ...........l                          \n");
	printf("                     l...... #### ..............l                          \n");
	printf("                     l........l.................l                          \n");
	printf("                     l........l..............www                           \n");
	printf("                     l........l...........www                              \n");
	printf("                      ＼......l........www                                 \n");
	printf("                         ＼...l.....www                                    \n");
	printf("                            ＼l__www                                       \n");
}

void print_menu() {
	printf("\n");
	printf("  ■■■■■  ■■■■    ■■■■■     ■■      ■■■■   ■      ■  ■■■■    ■■■■■\n");
	printf("      ■      ■     ■   ■            ■  ■    ■      ■  ■      ■  ■     ■   ■        \n");
	printf("      ■      ■     ■   ■            ■  ■    ■          ■      ■  ■     ■   ■        \n");
	printf("      ■      ■■■■    ■■■■■   ■■■■    ■■■■   ■      ■  ■■■■    ■■■■■\n");
	printf("      ■      ■    ■    ■          ■      ■          ■  ■      ■  ■    ■    ■        \n");
	printf("      ■      ■     ■   ■          ■      ■  ■      ■  ■      ■  ■     ■   ■        \n");
	printf("      ■      ■      ■  ■■■■■  ■      ■   ■■■■    ■■■■   ■      ■  ■■■■■\n\n");
	printf("                                                                  ■      ■  ■      ■  ■      ■  ■■■■■\n");
	printf("                    ######                                        ■      ■  ■      ■  ■■    ■      ■    \n");
	printf("                 ###......##                                      ■      ■  ■      ■  ■ ■   ■      ■    \n");
	printf("              ###...........##                                    ■■■■■  ■      ■  ■  ■  ■      ■    \n");
	printf("           ###...............##                                   ■      ■  ■      ■  ■   ■ ■      ■    \n");
	printf("       ####....................#                                  ■      ■  ■      ■  ■    ■■      ■    \n");
	printf("      #....#................###l                                  ■      ■   ■■■■   ■      ■      ■    \n");
	printf("     #......#............### ..l                                      \n");
	printf("    ##.......#........### .....l                                      \n");
	printf("    l ###....#.....### ........l         ┌ㅡㅡㅡㅡ   M E N U  ㅡㅡㅡㅡ┐\n");
	printf("    l... ###.#..### ...........l         ㅣ                           ㅣ\n");
	printf("    l...... #### ..............l         ㅣ          E A S Y          ㅣ\n");
	printf("    l........l.................l         ㅣ                           ㅣ\n");
	printf("    l........l..............www          ㅣ        N O R M A L        ㅣ\n");
	printf("    l........l...........www             ㅣ                           ㅣ\n");
	printf("     ＼......l........www                ㅣ          H A R D          ㅣ\n");
	printf("        ＼...l.....www                   ㅣ                           ㅣ \n");
	printf("           ＼l__www                      └ㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡ┘\n\n");
	printf("\n\n                                                                                            Press 'Q' or 'q' to Exit\n");
}

void box1(int x, const int y) {
	gotoxy(x++, y);
	printf("................................................");
	gotoxy(x++, y);
	printf("................................................");
	gotoxy(x++, y);
	printf("................................................");
	gotoxy(x++, y);
	printf("................................................");
	gotoxy(x++, y);
	printf("................................................");
	gotoxy(x++, y);
	printf("................................................");
	gotoxy(x++, y);
	printf(".........:****VV*::::::::::::::::******:........");
	gotoxy(x++, y);
	printf(".......:*VVVVFV*********************VVVVV*......");
	gotoxy(x++, y);
	printf("......:VVVVFIVVVVVVV*****V**********VVVVVFV:....");
	gotoxy(x++, y);
	printf(".....:VVVVVMV*************VVV**VV****VVVVVFV....");
	gotoxy(x++, y);
	printf(".....*FIFFIMFVVVVVVVVFFVVVVVVVVVVVVVVVVFIFII:...");
	gotoxy(x++, y);
	printf("....:VIIIIIMFVVVVVVVVVVVVVVVVVVVVVVVVVVIIIIM*...");
	gotoxy(x++, y);
	printf("....:VIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIV...");
	gotoxy(x++, y);
	printf("....:FIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIV...");
	gotoxy(x++, y);
	printf("....*VIIIIIIIIIIIIIIIIIIIIIIMIIIIIIIIIIIIIIIV:..");
	gotoxy(x++, y);
	printf("....*VVFFFFFFFFFFFFIVFFIIIFIMIFFFFFFFFFFFFVVV...");
	gotoxy(x++, y);
	printf("....:VFIIIIIIIIIIIIIVIIN$MIIMMIIIIIIIIIIIIFV*...");
	gotoxy(x++, y);
	printf(".....VIMMMNMMMMMMMMIVIIN$MIIMMMMMMMMMMMMMMMF....");
	gotoxy(x++, y);
	printf(".....VIMMMNMIIIMMMIIIMMMMMMMNNMMMMIIIMMMMMMV....");
	gotoxy(x++, y);
	printf(".....*IMMMNIVVVVVVVVFFFVVVVVVVVVVVVVVIMMMMMV....");
	gotoxy(x++, y);
	printf(".....*FMMMNMFFFFFFFFFFFFFFFIIIIIIIIIIMMMMMMV....");
	gotoxy(x++, y);
	printf(".....*IMMMNMFFFFFFFIIIIIIFFFFFFVFFFFFMMMMMM*....");
	gotoxy(x++, y);
	printf(".....*FMMMNMVVVVVVVVVVVVVVVVVVVVVVVVVMMMMMM*....");
	gotoxy(x++, y);
	printf(".....*FMMMMNFFFFFFVVVVVVVFFFFFFFFIIIIMMMMMM*....");
	gotoxy(x++, y);
	printf(".....*VVFIIIFFFFFFFFFFFFFFFFFFFFFFFFFIFFFFV*....");
	gotoxy(x++, y);
	printf("..::::VVIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIFV::::.");
	gotoxy(x++, y);
	printf("....::::*********************************::::...");
}

void box2(int x, const int y) {
	gotoxy(x++, y);
	printf("................................................");
	gotoxy(x++, y);
	printf("................................................");
	gotoxy(x++, y);
	printf("................................................");
	gotoxy(x++, y);
	printf("................................................");
	gotoxy(x++, y);
	printf("..........:*****:::::::::::::::::*****:.........");
	gotoxy(x++, y);
	printf(".......:*IIIVVI********************IIIVI*:......");
	gotoxy(x++, y);
	printf("......*IVVVFFIIIIIII****II*********IIVVVVV*.....");
	gotoxy(x++, y);
	printf(".....*VVVVVFI******IIIIIIIIIIIIIIIIIIIVVVVV*....");
	gotoxy(x++, y);
	printf("....*VFFFF$$VVVVVVVVVVVVVVIIIVVVVVVVVVFFFFFV....");
	gotoxy(x++, y);
	printf("....*VFFFFFFFVVVVVVVVVVVVVVVVVFFFFFFFVFFFFFF*...");
	gotoxy(x++, y);
	printf("....IFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF*...");
	gotoxy(x++, y);
	printf("....*FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF*...");
	gotoxy(x++, y);
	printf("....:*V$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$NFI*....");
	gotoxy(x++, y);
	printf("....*VNN$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$NNFI:...");
	gotoxy(x++, y);
	printf("...:IIVVVVVVVVVVVVVVVVVVVVVVFVVVVVVVVVVVVVVI*...");
	gotoxy(x++, y);
	printf("...:IVFFFFFFFFFFFFFVVFF$$FFF$FFFFFFFFFFFFFVV*...");
	gotoxy(x++, y);
	printf("....*VFFFFFFFFFFFFFVVFFMNFFFNFFFFFFFFFFFFFVI:...");
	gotoxy(x++, y);
	printf("....*F$$$NN$$$$$$$$VFFNMMFFFN$$$$FFFFNF$$$$*....");
	gotoxy(x++, y);
	printf("....*FFFFNNFFFFFFFFF$$$NN$$NNFFFFFFFF$FFFFN*....");
	gotoxy(x++, y);
	printf("....:VFFF$NVVVVVVVVVVVVVVVVVIIIIIIIIV$FFFFN*....");
	gotoxy(x++, y);
	printf("....:VFFF$NFVVVVFFFVVVFVFFFFFFFFFFFFF$FFFF$:....");
	gotoxy(x++, y);
	printf(".....IFFF$NFVVVVVVVVVVVVVVVVVVVVVVVVF$F$F$F:....");
	gotoxy(x++, y);
	printf(".....IFFF$NFVVVVIIIIIIIIIIIIIIIIIIIIVFFFF$V.....");
	gotoxy(x++, y);
	printf("....:IVF$$N$VVVVVVVVVVVVVVVVVVVFFFFF$FF$F$F*....");
	gotoxy(x++, y);
	printf("....:IVVFFFFFFFFFFFFFFFFFFFFFFFFFFFFFVFFFVI:....");
	gotoxy(x++, y);
	printf(".::::*IVFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFVI*:*::.");
	gotoxy(x++, y);
	printf("....:::::::::::::::::*********:::::::::::::::...");
}

void box3(int x, const int y) {
	gotoxy(x++, y);
	printf("................................................");
	gotoxy(x++, y);
	printf("................................................");
	gotoxy(x++, y);
	printf("................................................");
	gotoxy(x++, y);
	printf(".........:****I**::::::::::::::::*******:.......");
	gotoxy(x++, y);
	printf("......:*IIIIVVI**********IIIIIIIIIIIIIIIII*:....");
	gotoxy(x++, y);
	printf(".....:IIIIIFVIIIIIIIIIIIIIIIIIIIIIIIIIIIIIVI:...");
	gotoxy(x++, y);
	printf("....:IVVVVF$VVVVVVVVVVVVVVVVVVIVIIIIIIVVVVVFI...");
	gotoxy(x++, y);
	printf("....*FFFFF$$VFVVVVVVVVVVVVVVVVVVVVVVVVVFFFFFF:..");
	gotoxy(x++, y);
	printf("....IFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF$*..");
	gotoxy(x++, y);
	printf("....*VF$NNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNN$FFV:..");
	gotoxy(x++, y);
	printf(".....*VFNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNFV*:...");
	gotoxy(x++, y);
	printf("......*VFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFVI:....");
	gotoxy(x++, y);
	printf(".....*VNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNFI:...");
	gotoxy(x++, y);
	printf("....*I$NNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNV*:..");
	gotoxy(x++, y);
	printf("....IIVVVVVVVVVVVVVFVFVFVFVFFVVVVVVVVVVVVVVII:..");
	gotoxy(x++, y);
	printf("....*VVFFFFFFFFFFFFFVFFNN$FFN$FFFFFFFFFFFFFVI...");
	gotoxy(x++, y);
	printf("....:VFFFFFFFFFFFF$FVFFNM$FFN$FFFFFFFFFFFFFV*...");
	gotoxy(x++, y);
	printf("....:V$NNNMN$$NNNNNFVF$MMNFFNN$$$$$$$NN$NNNV....");
	gotoxy(x++, y);
	printf(".....IF$$NMFVVVVVVVFF$$$$$$$NFFFFFFFFN$$$$NV....");
	gotoxy(x++, y);
	printf(".....IF$$$N$VVVVVVVVVVVVVIIVVIIIVIVIIFF$$$NI....");
	gotoxy(x++, y);
	printf(".....IF$$$NNVVVFFFFFFFFFFFFFFFFFFFFFFNF$$$NI....");
	gotoxy(x++, y);
	printf(".....*F$$$NNFFVVVVVVVVVVVVVVVVVVVVVVV$F$$$N*....");
	gotoxy(x++, y);
	printf(".....*F$$$NNVVVVVVVVIIIIIVVVVVVVVVVVV$F$$$N*....");
	gotoxy(x++, y);
	printf(".....IVFFFNNFVVVVVVVVVVVVVVVVVVVVFFFF$FF$$$I....");
	gotoxy(x++, y);
	printf("...::*VVFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFVV*:::.");
	gotoxy(x++, y);
	printf(".:::***IVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVI*:*:::");
	gotoxy(x++, y);
	printf(".....:::::::::::::::::::::::::::::::::::::::....");
}

void box4(int x, const int y) {
	gotoxy(x++, y);
	printf("................................................");
	gotoxy(x++, y);
	printf("................................................");
	gotoxy(x++, y);
	printf("........::****I**:::::::::::::::::******:.......");
	gotoxy(x++, y);
	printf("......:*IIIIVVIIIIIIII**III***IIIIIIIIIIII*:....");
	gotoxy(x++, y);
	printf("....:*IIIIVFVIIIIIIIIIIIIIIIIIIIIIIIIIIIIIVV*...");
	gotoxy(x++, y);
	printf("....*VFFFF$$FFFFFFVVVVVVVVVVVVVVVVVVVVVFFFFFF:..");
	gotoxy(x++, y);
	printf("....IFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF$*..");
	gotoxy(x++, y);
	printf("....IVF$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$FVV:..");
	gotoxy(x++, y);
	printf("....:VFNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNMNNFV*...");
	gotoxy(x++, y);
	printf(".....*F$NNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNMN$FV:...");
	gotoxy(x++, y);
	printf(".....:VFNNNMNNNNNNNNNNNNNNNNNNNNNNNNNNNNNFV*....");
	gotoxy(x++, y);
	printf("......*VFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFVI:....");
	gotoxy(x++, y);
	printf(".....:*F$NNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNFI:....");
	gotoxy(x++, y);
	printf(".....*VNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNFI:...");
	gotoxy(x++, y);
	printf("....*IFN$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$N$VI:..");
	gotoxy(x++, y);
	printf("....*IVVVVVVVVVVVVVVVVVVVVVVFVVVVVVVVVVVVVVIV:..");
	gotoxy(x++, y);
	printf("....*VFFFFFFFFFFFFFFVFFNM$FFN$FFFFFFFFFFFFFVI...");
	gotoxy(x++, y);
	printf("....:VF$$$$$FFF$FF$FVFFNM$FFNN$$FFFFF$$$$$FV*...");
	gotoxy(x++, y);
	printf(".....IF$$NMNFF$$$$$FVF$NMNFFNN$$FFFFFN$$$$$V....");
	gotoxy(x++, y);
	printf(".....IF$$$NFVVVVVVVFFFFFFFFFFVVVVVVVVF$$$$NV....");
	gotoxy(x++, y);
	printf(".....*F$$$N$VVVVVVVVVVVVVVVFFFFFFFFFF$$$$$NI....");
	gotoxy(x++, y);
	printf(".....*F$$$NNFFFFFFFFFFFFFFFFVVVVVVVVV$$$$$NI....");
	gotoxy(x++, y);
	printf(".....*F$$$NNFVVVVVVVVVVIVVVVVVVVVVVVV$F$$$N*....");
	gotoxy(x++, y);
	printf(".....*F$$$NNVVVVVVVVVVVVVVVVVVFFFFFFFN$$$$N*....");
	gotoxy(x++, y);
	printf(".....IVVFFFFVVVVVVVVVVVVVVVVVVVVVVVVVFFFFFFI....");
	gotoxy(x++, y);
	printf("..:::*VVFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFVV*::::");
	gotoxy(x++, y);
	printf("..::::*IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII*:::::");
}

void box5(int x, const int y) {
	gotoxy(x++, y);
	printf("................................................");
	gotoxy(x++, y);
	printf("........::::****:::::::::::::::::::***:::.......");
	gotoxy(x++, y);
	printf(".....:**IIIVVIIIII*******I*****IIIIIIIIIII*:....");
	gotoxy(x++, y);
	printf("...:*VVVVVFFVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVF*...");
	gotoxy(x++, y);
	printf("...*VVFF$FFFFF$$F$$F$$$$$$$$$$$$$$$$$FF$FFFVI...");
	gotoxy(x++, y);
	printf("...:IFNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNFV*...");
	gotoxy(x++, y);
	printf("....*V$NNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNFV:...");
	gotoxy(x++, y);
	printf("....*VFNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNN$FI....");
	gotoxy(x++, y);
	printf(".....IFNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNFV*....");
	gotoxy(x++, y);
	printf(".....*V$NNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNFV:....");
	gotoxy(x++, y);
	printf(".....:VFNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNVI.....");
	gotoxy(x++, y);
	printf("......IVVFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFVV*.....");
	gotoxy(x++, y);
	printf(".....:IF$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$V*.....");
	gotoxy(x++, y);
	printf("....:IFNNNNNNNNNNNNNNNNNNN$$NNNNNNNNNNNNNNV*....");
	gotoxy(x++, y);
	printf("...:IV$$F$$$$$$$$F$$$$$$$$$$$$$$$$$$$$$F$$FI*...");
	gotoxy(x++, y);
	printf("...:IIVVVVVVVVVVVVVVVVVVVVVVFVVVVVVVVVVVVVVI*...");
	gotoxy(x++, y);
	printf("....IVFFFFFFFFFFFFFVFF$MNFFF$FFFFFFFFFFFFFVV*...");
	gotoxy(x++, y);
	printf("....*FFFF$$FFFFFFF$FFF$MNFFFNFFFFFFFFFFFFFFI....");
	gotoxy(x++, y);
	printf("....*F$$$NNFFFF$$$$FFFNNNFF$N$$FFFFFFNF$$$N*....");
	gotoxy(x++, y);
	printf("....*FF$$NNVVVVVVVVFFFFFFFFFVVVVVVVVV$F$$$N*....");
	gotoxy(x++, y);
	printf("....:VF$$NNFVVVVVVVVVVVVVVVFVFFFFFVFFNF$$$N:....");
	gotoxy(x++, y);
	printf("....:VF$$$NFVVVVVFFVVVVVVVVVVVVVVVVVFNF$$$$:....");
	gotoxy(x++, y);
	printf(".....IF$$$NFVVVVVVVVVIIIIIIIIIVVVVVVF$F$$$F.....");
	gotoxy(x++, y);
	printf(".....IF$$$NFVVVVVVVVVVVVVVVVVVVFFFFF$$F$$$F.....");
	gotoxy(x++, y);
	printf("....:VVFFFFFVVVVVVVVVVVVVVVVVVVVVVVVFFFFFFV*....");
	gotoxy(x++, y);
	printf(".::::*VVFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFVI::::.");
	gotoxy(x++, y);
	printf(".:::::*IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII**::::.");
}

void box6(int x, const int y) {
	gotoxy(x++, y);
	printf(".........::::***::::::::::::::::::::*::::.......");
	gotoxy(x++, y);
	printf(".....:*IIIIVFVVIIIIIIIIIIIIIIIIIIIIIIIIIIII*....");
	gotoxy(x++, y);
	printf("....:VVFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFVV*...");
	gotoxy(x++, y);
	printf("....*VFNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNFV*...");
	gotoxy(x++, y);
	printf("....:VFNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNFV*...");
	gotoxy(x++, y);
	printf(".....IFNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNFV:...");
	gotoxy(x++, y);
	printf(".....*FNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNN$FI....");
	gotoxy(x++, y);
	printf(".....*V$NNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNN$VI....");
	gotoxy(x++, y);
	printf(".....:VFNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNFV*....");
	gotoxy(x++, y);
	printf(".....:IFNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNFV*....");
	gotoxy(x++, y);
	printf("......IFNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNFV:....");
	gotoxy(x++, y);
	printf("......*VFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFVI.....");
	gotoxy(x++, y);
	printf("......*VFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFVI:....");
	gotoxy(x++, y);
	printf(".....*V$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$NV*:...");
	gotoxy(x++, y);
	printf("....*I$N$$$$FFF$$$$$$$$$$$FFF$F$$$$$$$$$$NNV*...");
	gotoxy(x++, y);
	printf("....*IVVVVVVVVVVVVVVVVVVVVVVFVVVVVVVVVVVVVVII:..");
	gotoxy(x++, y);
	printf("....*VVFFFFFFFFFFFFFVFFNNFFFNFFFFFFFFFFFFFFVI...");
	gotoxy(x++, y);
	printf("....:VFFFFFFFFFFFFFFVFFNMFFFN$FFFFFFFFFFFFFV*...");
	gotoxy(x++, y);
	printf("....:VF$$NMN$$$$$$$FVF$MM$FFNN$$$$$F$N$$$$$V....");
	gotoxy(x++, y);
	printf(".....IF$$$NFVVVFFFFFF$$$$$$$NFFFFFFFFN$$$$$V....");
	gotoxy(x++, y);
	printf(".....IF$$$N$VVVVVVVVVVVVIIIIVVIIIIVVVFF$$$NI....");
	gotoxy(x++, y);
	printf(".....IF$$$N$VVVFFFFFFFFFFFFFFFFFFFFFFNF$$$NI....");
	gotoxy(x++, y);
	printf(".....*F$$$NNVVVVVVVVVVVVVVVVVVVVVVVVV$F$$$N*....");
	gotoxy(x++, y);
	printf(".....*F$$$NNVVVVVVIIIIIIIIIIIIIIVVVVV$F$$$N*....");
	gotoxy(x++, y);
	printf(".....IVFFF$$VVVVVVVVVVVVVVVVVVVVVVVVF$FFFFFI....");
	gotoxy(x++, y);
	printf("...::*VVFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFVV*:::.");
	gotoxy(x++, y);
	printf(".:::**IVVVFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFVVI*:*::");
}

void success(const int x, const int y) {
	for (int i = 0; i < 2; i++)
	{
		box1(x, y);
		Sleep(150);
		erase_console();
		box2(x, y);
		Sleep(150);
		erase_console();
		box3(x, y);
		Sleep(150);
		erase_console();
		box4(x, y);
		Sleep(150);
		erase_console();
		box5(x, y);
		Sleep(150);
		erase_console();
		box6(x, y);
		Sleep(150);
		erase_console();
	}
	for (int i = 0; i < 4; i++)
	{
		box6(x, y);
		Sleep(250);
		erase_console();
		Sleep(150);
	}
}